
/*-------------------------------------- DDL ------------------------------------------*/
/* ------ CREACION DE TABLAS CON PK Y FK POR ORDEN DE JERARQUIA DE DEPENDENCIAS ------ */

/* ----------- 1 NIVEL DE JERARQUIA (no dependen d nadie)----------- */
CREATE TABLE Usuario(
    idUsuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombreUsuario VARCHAR2(50) NOT NULL,
    correo VARCHAR2(50) NOT NULL,
    password VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY(idUsuario)
);

/* ----------- 2 NIVEL DE JERARQUIA ----------- */
CREATE TABLE Lista(
    idLista NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fechaCreacion DATE NOT NULL,
    titulo VARCHAR2(30) NOT NULL,
    idUsuario NUMBER(10) NOT NULL,
    CONSTRAINT PK_Lista PRIMARY KEY(idLista),
    CONSTRAINT FK_Lista_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario)
);

CREATE TABLE Cancion(
    idCancion NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR2(50) NOT NULL,
    genero VARCHAR2(10) NOT NULL,
    calificacion NUMBER(10) NOT NULL,
    comentario VARCHAR2(300) NOT NULL,
    artista VARCHAR2(50) NOT NULL,
    album VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_Cancion PRIMARY KEY(idCancion),
    CONSTRAINT CKC_calificacion_Cancion CHECK(calificacion IN(1,2,3,4,5,6,7,8,9,10))
);

/* ----------- 3 NIVEL DE JERARQUIA ----------- */
CREATE TABLE CancionXLista(
    idLista NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXLista PRIMARY KEY(idLista, idCancion),
    CONSTRAINT FK_CancionXLista_Lista
        FOREIGN KEY(idLista) REFERENCES Lista(idLista),
    CONSTRAINT FK_CancionXLista_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);

CREATE TABLE CancionXUsuario(
    idUsuario NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXUsuario PRIMARY KEY(idUsuario, idCancion),
    CONSTRAINT FK_CancionXUsuario_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario),
    CONSTRAINT FK_CancionXUsuario_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);