-- Nivel 3 (dependen de otras)
DROP TABLE CancionXUsuario CASCADE CONSTRAINTS;
DROP TABLE CancionXLista CASCADE CONSTRAINTS;

-- Nivel 2
DROP TABLE Lista CASCADE CONSTRAINTS;
DROP TABLE Cancion CASCADE CONSTRAINTS;

-- Nivel 1 (padre)
DROP TABLE Usuario CASCADE CONSTRAINTS;

/*-------------------------------------- DDL ------------------------------------------*/
/* ------ CREACION DE TABLAS CON PK Y FK POR ORDEN DE JERARQUIA DE DEPENDENCIAS ------ */

/* ----------- 1 NIVEL DE JERARQUIA (no dependen d nadie)----------- */
CREATE TABLE Usuario(
    idUsuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombreUsuario VARCHAR2(50) NOT NULL,
    correo VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY(idUsuario)
);

/* ----------- 2 NIVEL DE JERARQUIA ----------- */
CREATE TABLE Lista(
    idLista NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fechaCreacion DATE NOT NULL,
    titulo VARCHAR2(30) NOT NULL,
    idUsuario NUMBER(10) NOT NULL,
    CONSTRAINT PK_Lista PRIMARY KEY(idLista),
    CONSTRAINT FK_Lista_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario)
);

CREATE TABLE Cancion(
    idCancion NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR2(50) NOT NULL,
    genero VARCHAR2(10) NOT NULL,
    calificacion NUMBER(10) NOT NULL,
    comentario VARCHAR2(300) NOT NULL,
    artista VARCHAR2(50) NOT NULL,
    album VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_Cancion PRIMARY KEY(idCancion),
    CONSTRAINT CKC_calificacion_Cancion CHECK(calificacion IN(1,2,3,4,5,6,7,8,9,10))
);

/* ----------- 3 NIVEL DE JERARQUIA ----------- */
CREATE TABLE CancionXLista(
    idLista NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXLista PRIMARY KEY(idLista, idCancion),
    CONSTRAINT FK_CancionXLista_Lista
        FOREIGN KEY(idLista) REFERENCES Lista(idLista),
    CONSTRAINT FK_CancionXLista_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);

CREATE TABLE CancionXUsuario(
    idUsuario NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXUsuario PRIMARY KEY(idUsuario, idCancion),
    CONSTRAINT FK_CancionXUsuario_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario),
    CONSTRAINT FK_CancionXUsuario_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);



/* ----------- LOGICA DE FUNCIONALIDADES ----------- */

/* ----------- REGISTAR USUARIO (PROCEDIMIENTO 1) ----------- */
/*
    Este procedimiento en el codigo va a recibir todos esos parametros y
    cuando los procese hace out del resultado, dependiendo de lo que haya 
    sucedido va a devolver un numero distinto y eso se va a usar para decidir
    como proceder en el codigo. Su funcion es registar el usuario segun la
    informacion recibida del formulario, simpre y cuando cumpla las condiciones.

    Simbologia de la variable out: p_resultado
        1 = correo ya registrado
        0 = registro exitoso
        2 = error general
*/
CREATE OR REPLACE PROCEDURE sp_registrar_usuario(
    p_nombreUsuario IN Usuario.nombreUsuario%TYPE,
    p_correo IN Usuario.correo%TYPE,
    p_password IN Usuario.password%TYPE,
    p_resultado OUT NUMBER
)
IS
    v_count NUMBER;
BEGIN
    -- Verifica si el correo ya existe
    SELECT COUNT(*)
    INTO v_count
    FROM Usuario
    WHERE correo = p_correo;

    IF v_count > 0 THEN
        p_resultado := 1;
    ELSE
        INSERT INTO Usuario(nombreUsuario, correo, password)
        VALUES (p_nombreUsuario, p_correo, p_password);

        p_resultado := 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        p_resultado := 2;
END;



/* ----------- LOGIN USUARIO (PROCEDIMIENTO 2) ----------- */
/* 
    Este procedimiento recibe el correo y password del usuario que hace
    login y busca y comprara para ver si el usuario existe. Dependiendo de 
    el resultado el codigo decidira como proceder. Este hace out de 3 
    valores, 2 son en caso de que el las credenciales sean correctas para 
    establecer esos valores en la session y el otro valor es el resultado.
    
    Simbologia de la variable out: p_resultado
        1 = credenciales incorrectas
        0 = login exitoso
        2 = error general
*/
CREATE OR REPLACE PROCEDURE sp_login_usuario(
    p_correo IN Usuario.correo%TYPE,
    p_password IN Usuario.password%TYPE,
    p_resultado OUT NUMBER,
    p_idUsuario OUT Usuario.idUsuario%TYPE,
    p_nombre OUT Usuario.nombreUsuario%TYPE
)
IS
BEGIN
    SELECT idUsuario, nombreUsuario
    INTO p_idUsuario, p_nombre
    FROM Usuario
    WHERE correo = p_correo
      AND password = p_password;

    p_resultado := 0;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_resultado := 1;

    WHEN OTHERS THEN
        p_resultado := 2;
END;



/* ----------- LOGICA DE LA PANTALLA DASHBOARD ----------- */

/* ----------- ESTADISTICAS DEL DASHBOARD (PROCEDIMIENTO 3)----------- */
/*
    Este procedimiento se usa para que cuando el usuario se logea le muestre
    en la pantalla del dashboard varias estadisticas. En el codigo recibe el
    id del usuario establecido en la session y lo usa para hacer out de los 3
    valores que se muestran en las estadistcas.
*/
CREATE OR REPLACE PROCEDURE sp_dashboard_stats(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_totalCanciones OUT NUMBER,
    p_totalArtistas OUT NUMBER,
    p_totalListas OUT NUMBER
)
IS
BEGIN
    /* Funcion de cada SELECT:
        - 1 Total canciones del usuario
        - 2 Total artistas distintos
        - 3 Total listas
    */
    SELECT COUNT(*)
    INTO p_totalCanciones
    FROM CancionXUsuario
    WHERE idUsuario = p_idUsuario;


    SELECT COUNT(DISTINCT c.artista)
    INTO p_totalArtistas
    FROM Cancion c
        JOIN CancionXUsuario cu ON c.idCancion = cu.idCancion
    WHERE cu.idUsuario = p_idUsuario;


    SELECT COUNT(*)
    INTO p_totalListas
    FROM Lista
    WHERE idUsuario = p_idUsuario;

EXCEPTION
    WHEN OTHERS THEN
    -- Por aquello de que truene devuelve 0 en todo 
        p_totalCanciones := 0;
        p_totalArtistas := 0;
        p_totalListas := 0;
END;



/* ----------- OBTENER CANCIONES DEL USUARIO (FUNCION 1) ----------- */
/*
    Esta funcion se encarga de retornar  todas las canciones del usuario
    en un cursor para mostarlas en la pnatalla de dashboard.
    Recibe el id que esta seteado en la session, para obtener las canciones
    del usuario. Cuando se retorna el cursor, en el codigo se recorre para 
    generar dinamicamente los elemtos visuales de cada cancion osea obtener
    su informacion.
*/
CREATE OR REPLACE FUNCTION fn_obtener_canciones_usuario(
    p_idUsuario IN Usuario.idUsuario%TYPE
) RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.idCancion,
            c.titulo,
            c.artista,
            c.album,
            c.genero,
            c.calificacion
        FROM Cancion c
        JOIN CancionXUsuario cu ON c.idCancion = cu.idCancion
        WHERE cu.idUsuario = p_idUsuario;

    RETURN v_cursor;
END;
