
/*-------------------------------------- DDL ------------------------------------------*/
/* ------ CREACION DE TABLAS CON PK Y FK POR ORDEN DE JERARQUIA DE DEPENDENCIAS ------ */

/* ----------- 1 NIVEL DE JERARQUIA (no dependen d nadie)----------- */
CREATE TABLE Usuario(
    idUsuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombreUsuario VARCHAR2(50) NOT NULL,
    correo VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY(idUsuario)
);

/* ----------- 2 NIVEL DE JERARQUIA ----------- */
CREATE TABLE Lista(
    idLista NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fechaCreacion DATE NOT NULL,
    titulo VARCHAR2(30) NOT NULL,
    idUsuario NUMBER(10) NOT NULL,
    CONSTRAINT PK_Lista PRIMARY KEY(idLista),
    CONSTRAINT FK_Lista_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario)
);

CREATE TABLE Cancion(
    idCancion NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR2(50) NOT NULL,
    genero VARCHAR2(30) NOT NULL,
    calificacion NUMBER(10,0) NOT NULL,
    comentario VARCHAR2(300) NOT NULL,
    artista VARCHAR2(50) NOT NULL,
    album VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_Cancion PRIMARY KEY(idCancion),
    CONSTRAINT CKC_calificacion_Cancion CHECK(calificacion IN(1,2,3,4,5,6,7,8,9,10))
);


/* ----------- 3 NIVEL DE JERARQUIA ----------- */
CREATE TABLE CancionXLista(
    idLista NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXLista PRIMARY KEY(idLista, idCancion),
    CONSTRAINT FK_CancionXLista_Lista
        FOREIGN KEY(idLista) REFERENCES Lista(idLista),
    CONSTRAINT FK_CancionXLista_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);

CREATE TABLE CancionXUsuario(
    idUsuario NUMBER(10) NOT NULL,
    idCancion NUMBER(10) NOT NULL,
    CONSTRAINT PK_CancionXUsuario PRIMARY KEY(idUsuario, idCancion),
    CONSTRAINT FK_CancionXUsuario_Usuario
        FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario),
    CONSTRAINT FK_CancionXUsuario_Cancion
        FOREIGN KEY(idCancion) REFERENCES Cancion(idCancion)
);

-- DROPS por aquello
/* ----------- 3 NIVEL DE JERARQUIA ----------- */
DROP TABLE CancionXUsuario CASCADE CONSTRAINTS;
DROP TABLE CancionXLista CASCADE CONSTRAINTS;

/* ----------- 2 NIVEL DE JERARQUIA ----------- */
DROP TABLE Cancion CASCADE CONSTRAINTS;
DROP TABLE Lista CASCADE CONSTRAINTS;

/* ----------- 1 NIVEL DE JERARQUIA ----------- */
DROP TABLE Usuario CASCADE CONSTRAINTS;


/* ----------- LOGICA CRUD ----------- */
/* 
    Este procedimiento es para actualizar los datos en la tabla usuario
    por ahora se usan en:
        - Funcionalidad del perfil para actualizar datos.
*/
CREATE OR REPLACE PROCEDURE SP_UPDATE_USUARIO(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_nombre IN Usuario.nombreUsuario%TYPE,
    p_correo IN Usuario.correo%TYPE
)
IS
BEGIN
    UPDATE Usuario
    SET nombreUsuario = p_nombre,
        correo = p_correo
    WHERE idUsuario = p_idUsuario;

    COMMIT;
END;


/*
    Este procedimiento lo que hace es eliminar al usuario que recibe como parametro
    pero antes de hacerlo elimina las coincidencias de este user en
    las otras tablas, osea elimina sus relaciones para evitar conflictos de 
    dependencias, una vez hecho eso elimina al usuario
*/
CREATE OR REPLACE PROCEDURE SP_DELETE_USUARIO(
    p_idUsuario IN  Usuario.idUsuario%TYPE,
    p_resultado OUT NUMBER
)
IS
BEGIN
    -- Eliminar canciones de sus listas
    DELETE FROM CancionXLista
    WHERE idLista IN (SELECT idLista FROM Lista WHERE idUsuario = p_idUsuario);

    -- Eliminar sus listas
    DELETE FROM Lista WHERE idUsuario = p_idUsuario;

    -- Eliminar sus relaciones con canciones
    DELETE FROM CancionXUsuario WHERE idUsuario = p_idUsuario;

    -- Eliminar el usuario
    DELETE FROM Usuario WHERE idUsuario = p_idUsuario;

    COMMIT;
    p_resultado := 0;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_resultado := 2;
END;


/*
    Este lo que hace que recibe un id y devuelve toda la informacion relacionada
    de esa coincidencia en la tabla cancion. Esto para obtener una cancion en especifico.
*/
CREATE OR REPLACE PROCEDURE SP_GET_CANCION(
    p_idCancion IN Cancion.idCancion%TYPE,
    p_titulo OUT Cancion.titulo%TYPE,
    p_artista OUT Cancion.artista%TYPE,
    p_album OUT Cancion.album%TYPE,
    p_genero OUT Cancion.genero%TYPE,
    p_calificacion OUT Cancion.calificacion%TYPE,
    p_comentario OUT Cancion.comentario%TYPE
)
IS
BEGIN
    SELECT titulo, artista, album, genero, calificacion, comentario
    INTO p_titulo, p_artista, p_album, p_genero, p_calificacion, p_comentario
    FROM Cancion
    WHERE idCancion = p_idCancion;
END;


/*
    Este procedimeinto recibe los cambios para una cancion y realiza la actualizacion
*/
CREATE OR REPLACE PROCEDURE SP_UPDATE_CANCION(
    p_idCancion IN Cancion.idCancion%TYPE,
    p_titulo IN Cancion.titulo%TYPE,
    p_artista IN Cancion.artista%TYPE,
    p_album IN Cancion.album%TYPE,
    p_genero IN Cancion.genero%TYPE,
    p_calificacion IN Cancion.calificacion%TYPE,
    p_comentario IN Cancion.comentario%TYPE
)
IS
BEGIN
    UPDATE Cancion
    SET titulo = p_titulo,
        artista = p_artista,
        album = p_album,
        genero = p_genero,
        calificacion = p_calificacion,
        comentario = p_comentario
    WHERE idCancion = p_idCancion;

    COMMIT;
END;


/*
    Este procedimeinto elimina una cancion, pero antes elimina sus 
    dependencias en otras tablas para evitar conflictos.
*/
CREATE OR REPLACE PROCEDURE SP_DELETE_CANCION(
    p_idCancion IN Cancion.idCancion%TYPE
)
IS
BEGIN
    -- Eliminar relaciones con listas
    DELETE FROM CancionXLista
    WHERE idCancion = p_idCancion;

    -- Eliminar relación con usuario
    DELETE FROM CancionXUsuario
    WHERE idCancion = p_idCancion;

    -- Eliminar canción
    DELETE FROM Cancion
    WHERE idCancion = p_idCancion;

    COMMIT;
END;
/* ----------- LOGICA DE FUNCIONALIDADES DEL SISTEMA ----------- */
/*
    Quiero aclarar que se usa mucho porocedimiento con OUT poruq en php se 
    puede enlazar una variable con un parametro de una consulta para que en 
    el momento que se ejecuta la consulta esa variable guarde el valor al
    que esta enlazado automaticamente, los cursores solo se van a usar en 
    funciones que tengan que devolver varios registros, en el caso de datos
    simples se va a usar OUT en procedimientos.
*/

/* ----------- LOGICA DE VALIDACION Y AUTENTICACION ----------- */

/* ----------- REGISTAR USUARIO (PROCEDIMIENTO 1) ----------- */
/*
    Este procedimiento en el codigo va a recibir todos esos parametros y
    cuando los procese hace out del resultado, dependiendo de lo que haya 
    sucedido va a devolver un numero distinto y eso se va a usar para decidir
    como proceder en el codigo. Su funcion es registar el usuario segun la
    informacion recibida del formulario, simpre y cuando cumpla las condiciones.

    Simbologia de la variable out: p_resultado
        1 = correo ya registrado
        0 = registro exitoso
        2 = error general
*/
CREATE OR REPLACE PROCEDURE sp_registrar_usuario(
    p_nombreUsuario IN Usuario.nombreUsuario%TYPE,
    p_correo IN Usuario.correo%TYPE,
    p_password IN Usuario.password%TYPE,
    p_resultado OUT NUMBER
)
IS
    v_count NUMBER;
BEGIN
    -- Verifica si el correo ya existe
    SELECT COUNT(*)
    INTO v_count
    FROM Usuario
    WHERE correo = p_correo;

    IF v_count > 0 THEN
        p_resultado := 1;
    ELSE
        INSERT INTO Usuario(nombreUsuario, correo, password)
        VALUES (p_nombreUsuario, p_correo, p_password);

        p_resultado := 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        p_resultado := 2;
END;


/* ----------- LOGIN USUARIO (PROCEDIMIENTO 2) ----------- */
/* 
    Este procedimiento recibe el correo y password del usuario que hace
    login y busca y comprara para ver si el usuario existe. Dependiendo de 
    el resultado el codigo decidira como proceder. Este hace out de 3 
    valores, 2 son en caso de que el las credenciales sean correctas para 
    establecer esos valores en la session y el otro valor es el resultado.
    
    Simbologia de la variable out: p_resultado
        1 = credenciales incorrectas
        0 = login exitoso
        2 = error general
*/
CREATE OR REPLACE PROCEDURE sp_login_usuario(
    p_correo IN Usuario.correo%TYPE,
    p_password IN Usuario.password%TYPE,
    p_resultado OUT NUMBER,
    p_idUsuario OUT Usuario.idUsuario%TYPE,
    p_nombre OUT Usuario.nombreUsuario%TYPE
)
IS
BEGIN
    SELECT idUsuario, nombreUsuario
    INTO p_idUsuario, p_nombre
    FROM Usuario
    WHERE correo = p_correo
      AND password = p_password;

    p_resultado := 0;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_resultado := 1;

    WHEN OTHERS THEN
        p_resultado := 2;
END;



/* ----------- LOGICA DE LA PANTALLA DASHBOARD ----------- */

/* ----------- ESTADISTICAS DEL DASHBOARD (PROCEDIMIENTO 3)----------- */
/*
    Este procedimiento se usa para que cuando el usuario se logea le muestre
    en la pantalla del dashboard varias estadisticas. En el codigo recibe el
    id del usuario establecido en la session y lo usa para hacer out de los 3
    valores que se muestran en las estadistcas.
*/
CREATE OR REPLACE PROCEDURE sp_dashboard_stats(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_totalCanciones OUT NUMBER,
    p_totalArtistas OUT NUMBER,
    p_totalListas OUT NUMBER
)
IS
BEGIN
    /* Funcion de cada SELECT:
        - 1 Total canciones del usuario
        - 2 Total artistas distintos
        - 3 Total listas
    */
    SELECT COUNT(*)
    INTO p_totalCanciones
    FROM CancionXUsuario
    WHERE idUsuario = p_idUsuario;


    SELECT COUNT(DISTINCT c.artista)
    INTO p_totalArtistas
    FROM Cancion c
        JOIN CancionXUsuario cu ON c.idCancion = cu.idCancion
    WHERE cu.idUsuario = p_idUsuario;


    SELECT COUNT(*)
    INTO p_totalListas
    FROM Lista
    WHERE idUsuario = p_idUsuario;

EXCEPTION
    WHEN OTHERS THEN
    -- Por aquello de que truene devuelve 0 en todo 
        p_totalCanciones := 0;
        p_totalArtistas := 0;
        p_totalListas := 0;
END;



/* ----------- OBTENER CANCIONES DEL USUARIO (FUNCION 1) ----------- */
/*
    Esta funcion se encarga de retornar  todas las canciones del usuario
    en un cursor para mostarlas en la pnatalla de dashboard.
    Recibe el id que esta seteado en la session, para obtener las canciones
    del usuario. Cuando se retorna el cursor, en el codigo se recorre para 
    generar dinamicamente los elemtos visuales de cada cancion osea obtener
    su informacion.
*/
CREATE OR REPLACE FUNCTION fn_obtener_canciones_usuario(
    p_idUsuario IN Usuario.idUsuario%TYPE
) RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.idCancion,
            c.titulo,
            c.artista,
            c.album,
            c.genero,
            c.calificacion
        FROM Cancion c
        JOIN CancionXUsuario cu ON c.idCancion = cu.idCancion
        WHERE cu.idUsuario = p_idUsuario;

    RETURN v_cursor;
END;


/* ----------- LOGICA DE LA PANTALLA PERFIL ----------- */

/* ----------- OBTENER DATOS DEL USUARIO (PROCEDIMIENTO 4 + SUBCONSULTAS)----------- */
/*
    Este procedimiento toma el id del usuario que esta en la session y lo usa para obtener sus
    datos. Estos datos en el codigo se asignan a variables y luego se usan para rellenar los
    campos del formulario del perfil y del card de la info. Esto para que el usuario sepa cual
    es su informacion personal a la hora de cambiarla para actualizarla.
*/
CREATE OR REPLACE PROCEDURE SP_GET_USUARIO(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_nombre OUT Usuario.nombreUsuario%TYPE,
    p_correo OUT Usuario.correo%TYPE,
    p_totalCanciones OUT NUMBER,
    p_totalListas OUT NUMBER
)
IS
BEGIN
    SELECT 
        u.nombreUsuario,
        u.correo,
        -- Subconsulta canciones
        (SELECT COUNT(*)
         FROM CancionXUsuario cu
         WHERE cu.idUsuario = u.idUsuario),
        -- Subconsulta listas
        (SELECT COUNT(*)
         FROM Lista l
         WHERE l.idUsuario = u.idUsuario)
    INTO 
        p_nombre,
        p_correo,
        p_totalCanciones,
        p_totalListas
    FROM Usuario u
    WHERE u.idUsuario = p_idUsuario;
END;


/* ----------- LOGICA DE AGREGAR CANCION ----------- */

/*
    Este procedimeinto recibe las datos para agregar una cancion nueva y la relaciona
    con su usuario, osea el creador de la cancion.
*/
CREATE OR REPLACE PROCEDURE SP_INSERT_CANCION(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_titulo IN Cancion.titulo%TYPE,
    p_genero IN Cancion.genero%TYPE,
    p_calificacion IN Cancion.calificacion%TYPE,
    p_comentario IN Cancion.comentario%TYPE,
    p_artista IN Cancion.artista%TYPE,
    p_album IN Cancion.album%TYPE
)
IS
    v_idCancion Cancion.idCancion%TYPE;
BEGIN
    -- Insertar canción
    INSERT INTO Cancion (titulo, genero, calificacion, comentario, artista, album)
    VALUES (p_titulo, p_genero, p_calificacion, p_comentario, p_artista, p_album)
    RETURNING idCancion INTO v_idCancion;

    -- Relacionar con usuario
    INSERT INTO CancionXUsuario (idUsuario, idCancion)
    VALUES (p_idUsuario, v_idCancion);

    COMMIT;
END;


/*
    Este procedimento agrega a una lista la cancion, para eso usa
    el id de la cancion y la lista a la que va a ser agregada.
    Si la cancion ya existia no hace nada, si no existe la agrega.
*/
CREATE OR REPLACE PROCEDURE sp_agregar_cancion_a_lista(
    p_idLista   IN CancionXLista.idLista%TYPE,
    p_idCancion IN CancionXLista.idCancion%TYPE
)
IS
    v_count NUMBER;
BEGIN
    -- Verificar si ya existe
    SELECT COUNT(*)
    INTO v_count
    FROM CancionXLista
    WHERE idLista = p_idLista
      AND idCancion = p_idCancion;

    -- Si no existe, insertar
    IF v_count = 0 THEN
        INSERT INTO CancionXLista(idLista, idCancion)
        VALUES (p_idLista, p_idCancion);
    END IF;

END;





---Logica Cristhian

/* ----------- OBTENER DATOS DE UNA LISTA (PROCEDIMIENTO) Playlist----------- */
/*
    Recibe el idLista y devuelve el titulo, fecha y total de canciones.
    Se usa en playlist.php para mostrar el header de la lista.
*/
CREATE OR REPLACE PROCEDURE SP_GET_LISTA(
    p_idLista IN Lista.idLista%TYPE,
    p_titulo OUT Lista.titulo%TYPE,
    p_fechaCreacion OUT Lista.fechaCreacion%TYPE,
    p_totalCanciones OUT NUMBER
)
IS
BEGIN
    SELECT 
        l.titulo,
        l.fechaCreacion,
        (SELECT COUNT(*) FROM CancionXLista cl WHERE cl.idLista = l.idLista)
    INTO p_titulo, p_fechaCreacion, p_totalCanciones
    FROM Lista l
    WHERE l.idLista = p_idLista;
END;


/* ----------- OBTENER CANCIONES DE UNA LISTA (FUNCION) ----------- */
/*
    Retorna un cursor con todas las canciones de una lista especifica.
    Se recorre en PHP para generar dinamicamente las filas de la tabla.
*/
CREATE OR REPLACE FUNCTION fn_obtener_canciones_lista(
    p_idLista IN Lista.idLista%TYPE
) RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.idCancion,
            c.titulo,
            c.artista,
            c.album,
            c.genero,
            c.calificacion
        FROM Cancion c
        JOIN CancionXLista cl ON c.idCancion = cl.idCancion
        WHERE cl.idLista = p_idLista;

    RETURN v_cursor;
END;


/* ----------- ELIMINAR LISTA (PROCEDIMIENTO) ----------- */
/*
    Elimina primero las relaciones en CancionXLista y luego la lista.
    Simbologia p_resultado:
        0 = eliminacion exitosa
        2 = error general
*/
CREATE OR REPLACE PROCEDURE SP_DELETE_LISTA(
    p_idLista IN Lista.idLista%TYPE,
    p_resultado OUT NUMBER
)
IS
BEGIN
    DELETE FROM CancionXLista
    WHERE idLista = p_idLista;

    DELETE FROM Lista
    WHERE idLista = p_idLista;

    COMMIT;
    p_resultado := 0;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_resultado := 2;
END;
/* ----------- INSERTAR LISTA (PROCEDIMIENTO) -----------Addplailist */
/*
    Recibe el titulo y el idUsuario, inserta la lista con la fecha
    actual y devuelve el resultado.

    Simbologia p_resultado:
        0 = creacion exitosa
        2 = error general
*/
CREATE OR REPLACE PROCEDURE SP_INSERT_LISTA(
    p_idUsuario IN Lista.idUsuario%TYPE,
    p_titulo IN Lista.titulo%TYPE,
    p_resultado OUT NUMBER
)
IS
BEGIN
    INSERT INTO Lista (fechaCreacion, titulo, idUsuario)
    VALUES (SYSDATE, p_titulo, p_idUsuario);

    COMMIT;
    p_resultado := 0;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_resultado := 2;
END;
/* ----------- OBTENER LISTAS DEL USUARIO (FUNCION) Library----------- */
/*
    Retorna un cursor con todas las listas del usuario y el total
    de canciones de cada una. Se recorre en PHP para generar
    dinamicamente las cards de la libreria.
*/
CREATE OR REPLACE FUNCTION fn_obtener_listas_usuario(
    p_idUsuario IN Usuario.idUsuario%TYPE
) RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            l.idLista,
            l.titulo,
            l.fechaCreacion,
            (SELECT COUNT(*) 
             FROM CancionXLista cl 
             WHERE cl.idLista = l.idLista) AS totalCanciones
        FROM Lista l
        WHERE l.idUsuario = p_idUsuario
        ORDER BY l.fechaCreacion DESC;

    RETURN v_cursor;
END;
/* ----------- ELIMINAR CANCION DE UNA LISTA (PROCEDIMIENTO) DeleteSongFromList----------- */
/*
    Elimina la relacion entre una cancion y una lista en CancionXLista.
    No elimina la cancion en si, solo la quita de la lista.

    Simbologia p_resultado:
        0 = eliminacion exitosa
        2 = error general
*/
CREATE OR REPLACE PROCEDURE SP_REMOVE_CANCION_LISTA(
    p_idLista IN CancionXLista.idLista%TYPE,
    p_idCancion IN CancionXLista.idCancion%TYPE,
    p_resultado OUT NUMBER
)
IS
BEGIN
    DELETE FROM CancionXLista
    WHERE idLista = p_idLista
      AND idCancion = p_idCancion;

    COMMIT;
    p_resultado := 0;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_resultado := 2;
END;
/* ----------- BUSCAR CANCIONES POR TITULO (FUNCION) Search----------- */
/*
    Busca canciones del usuario que coincidan con el titulo ingresado.
    Usa LIKE para busqueda parcial, retorna cursor con los resultados.
*/
CREATE OR REPLACE FUNCTION fn_buscar_canciones(
    p_idUsuario IN Usuario.idUsuario%TYPE,
    p_busqueda IN VARCHAR2
) RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.idCancion,
            c.titulo,
            c.artista,
            c.album,
            c.genero,
            c.calificacion
        FROM Cancion c
        JOIN CancionXUsuario cu ON c.idCancion = cu.idCancion
        WHERE cu.idUsuario = p_idUsuario
          AND UPPER(c.titulo) LIKE UPPER('%' || p_busqueda || '%')
        ORDER BY c.titulo ASC;

    RETURN v_cursor;
END;






/* ------------------------------ Rodrigo*/
/* ---------------------- TRIGGERS ---------------------- */



-- TRIGGER 1: Validacion de calificacion antes de insertar o actualizar una cancion
-- Si la calificacion esta fuera del rango 1-10 lanza un error y cancela la operacion.
CREATE OR REPLACE TRIGGER trg_validar_calificacion
BEFORE INSERT OR UPDATE ON Cancion
FOR EACH ROW
BEGIN
    IF :NEW.calificacion < 1 OR :NEW.calificacion > 10 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Error: La calificacion debe estar entre 1 y 10. Valor recibido: ' || :NEW.calificacion);
    END IF;
END;


-- TRIGGER 2: Normalizacion de datos - convierte titulo y artista a formato titulo (primera letra mayuscula)
-- Se ejecuta antes de insertar o actualizar en Cancion para mantener consistencia en los datos.
CREATE OR REPLACE TRIGGER trg_normalizar_cancion
BEFORE INSERT OR UPDATE ON Cancion
FOR EACH ROW
BEGIN
    -- Convierte el titulo a mayusculas iniciales
    :NEW.titulo  := INITCAP(:NEW.titulo);
    -- Convierte el artista a mayusculas iniciales
    :NEW.artista := INITCAP(:NEW.artista);
    -- Convierte el album a mayusculas iniciales
    :NEW.album   := INITCAP(:NEW.album);
    -- Convierte el genero a mayuscula inicial
    :NEW.genero  := INITCAP(:NEW.genero);
END;


-- TRIGGER 3: Validacion de correo en Usuario
-- Verifica que el correo tenga un formato valido (contenga @ y un punto) antes de insertar o actualizar.
CREATE OR REPLACE TRIGGER trg_validar_correo_usuario
BEFORE INSERT OR UPDATE ON Usuario
FOR EACH ROW
BEGIN
    IF INSTR(:NEW.correo, '@') = 0 OR INSTR(:NEW.correo, '.') = 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'Error: El correo ingresado no tiene un formato valido: ' || :NEW.correo);
    END IF;
END;


-- TRIGGER 4: Validacion de titulo de lista no vacio
-- Impide que se inserte o actualice una lista con titulo en blanco o solo espacios.
CREATE OR REPLACE TRIGGER trg_validar_titulo_lista
BEFORE INSERT OR UPDATE ON Lista
FOR EACH ROW
BEGIN
    IF TRIM(:NEW.titulo) IS NULL OR LENGTH(TRIM(:NEW.titulo)) = 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Error: El titulo de la lista no puede estar vacio.');
    END IF;

    -- Normaliza el titulo quitando espacios extras
    :NEW.titulo := TRIM(:NEW.titulo);
END;


-- TRIGGER 5: Fecha automatica en Lista
-- Asigna automaticamente la fecha actual si no se proporciona una al insertar.
CREATE OR REPLACE TRIGGER trg_fecha_lista
BEFORE INSERT ON Lista
FOR EACH ROW
BEGIN
    IF :NEW.fechaCreacion IS NULL THEN
        :NEW.fechaCreacion := SYSDATE;
    END IF;
END;





/* ---------------------- VISTAS ---------------------- */
SET SERVEROUTPUT ON;



-- VISTA 1: Resumen completo de canciones por usuario
-- Muestra cada usuario con el total de canciones, artistas distintos,
-- su cancion mejor calificada y el promedio de calificaciones.
CREATE OR REPLACE VIEW vw_resumen_usuario AS
    SELECT
        u.idUsuario,
        u.nombreUsuario,
        u.correo,
        COUNT(c.idCancion) AS total_canciones,
        COUNT(DISTINCT c.artista)AS total_artistas,
        ROUND(AVG(c.calificacion), 2) AS promedio_calificacion,
        MAX(c.calificacion) AS mejor_calificacion,
        MIN(c.calificacion) AS peor_calificacion,
        (SELECT COUNT(*) FROM Lista l
         WHERE l.idUsuario = u.idUsuario) AS total_listas
    FROM Usuario u
    LEFT JOIN CancionXUsuario cu ON u.idUsuario = cu.idUsuario
    LEFT JOIN Cancion c ON cu.idCancion = c.idCancion
    GROUP BY u.idUsuario, u.nombreUsuario, u.correo;

-- Bloque anonimo para probar la vista
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== RESUMEN DE USUARIOS =====');

    FOR r IN (
        SELECT *
        FROM vw_resumen_usuario
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Usuario: ' || r.nombreUsuario ||
            ' | Correo: ' || r.correo ||
            ' | Canciones: ' || r.total_canciones ||
            ' | Artistas: ' || r.total_artistas ||
            ' | Promedio: ' || r.promedio_calificacion ||
            ' | Mejor: ' || r.mejor_calificacion ||
            ' | Peor: ' || r.peor_calificacion ||
            ' | Listas: ' || r.total_listas
        );
    END LOOP;
END;




-- VISTA 2: Detalle completo de listas con informacion de canciones
-- Muestra cada lista con su usuario dueno, la cantidad de canciones,
-- el promedio de calificacion de las canciones que contiene
-- y los generos musicales presentes en ella.
CREATE OR REPLACE VIEW vw_detalle_listas AS
    SELECT
        l.idLista,
        l.titulo AS titulo_lista,
        l.fechaCreacion,
        u.idUsuario,
        u.nombreUsuario,
        COUNT(cl.idCancion) AS total_canciones,
        ROUND(AVG(c.calificacion), 2) AS promedio_calificacion,
        MAX(c.calificacion) AS cancion_mejor_calif,
        -- Subconsulta: cantidad de generos distintos en la lista
        (SELECT COUNT(DISTINCT c2.genero)
         FROM Cancion c2
         JOIN CancionXLista cl2 ON c2.idCancion = cl2.idCancion
         WHERE cl2.idLista = l.idLista) AS total_generos_distintos
    FROM Lista l
    JOIN Usuario u ON l.idUsuario  = u.idUsuario
    LEFT JOIN CancionXLista cl ON l.idLista = cl.idLista
    LEFT JOIN Cancion c ON cl.idCancion = c.idCancion
    GROUP BY l.idLista, l.titulo, l.fechaCreacion, u.idUsuario, u.nombreUsuario;


-- Bloque anonimo para probar la vista
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== DETALLE DE LISTAS =====');

    FOR r IN (
        SELECT *
        FROM vw_detalle_listas
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Lista: ' || r.titulo_lista ||
            ' | Usuario: ' || r.nombreUsuario ||
            ' | Fecha: ' || TO_CHAR(r.fechaCreacion, 'DD/MM/YYYY') ||
            ' | Canciones: ' || r.total_canciones ||
            ' | Promedio: ' || r.promedio_calificacion ||
            ' | Mejor Calif: ' || r.cancion_mejor_calif ||
            ' | Generos Distintos: ' || r.total_generos_distintos
        );
    END LOOP;
END;




-- VISTA 3: Ranking de canciones mas agregadas en listas
-- Muestra que canciones aparecen en mas listas de usuarios distintos,
-- junto con su informacion completa y estadisticas de calificacion.
CREATE OR REPLACE VIEW vw_ranking_canciones AS
    SELECT
        c.idCancion,
        c.titulo,
        c.artista,
        c.album,
        c.genero,
        c.calificacion,
        -- Total de usuarios que tienen esta cancion en su libreria
        (SELECT COUNT(*)
         FROM CancionXUsuario cu2
         WHERE cu2.idCancion = c.idCancion) AS total_usuarios_con_cancion,
        -- Total de listas en las que aparece esta cancion
        COUNT(cl.idLista) AS total_listas_incluida,
        -- Clasificacion segun calificacion
        CASE
            WHEN c.calificacion >= 8 THEN 'Excelente'
            WHEN c.calificacion >= 5 THEN 'Regular'
            ELSE 'Baja'
        END AS clasificacion
    FROM Cancion c
    LEFT JOIN CancionXLista cl ON c.idCancion = cl.idCancion
    GROUP BY c.idCancion, c.titulo, c.artista, c.album, c.genero, c.calificacion
    ORDER BY total_listas_incluida DESC, c.calificacion DESC;


-- Bloque anonimo para probar la vista
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('===== RANKING DE CANCIONES =====');

    FOR r IN (
        SELECT *
        FROM vw_ranking_canciones
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Cancion: ' || r.titulo ||
            ' | Artista: ' || r.artista ||
            ' | Album: ' || r.album ||
            ' | Genero: ' || r.genero ||
            ' | Calif: ' || r.calificacion ||
            ' | Usuarios: ' || r.total_usuarios_con_cancion ||
            ' | Listas: ' || r.total_listas_incluida ||
            ' | Clasificacion: ' || r.clasificacion
        );
    END LOOP;
END;
    
-- Fin del documento